/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        'surface-bright': '#f9f9f9',
        outline: '#877270',
        'tertiary-fixed-dim': '#e1c0a7',
        'inverse-on-surface': '#f1f1f1',
        secondary: '#775a19',
        'on-background': '#1a1c1c',
        'subtle-gold': '#C5A059',
        'on-primary': '#ffffff',
        'surface-variant': '#e2e2e2',
        'off-white': '#F9F9F9',
        'industrial-taupe': '#8C715B',
        'surface-container-low': '#f3f3f3',
        'tertiary-container': '#33200f',
        'secondary-fixed': '#ffdea5',
        'surface-container-high': '#e8e8e8',
        'surface-tint': '#954742',
        'primary-fixed': '#ffdad7',
        'secondary-container': '#fed488',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#e9c176',
        'text-main': '#1A1A1A',
        'on-primary-container': '#cc726d',
        'on-tertiary-fixed': '#291808',
        'primary-fixed-dim': '#ffb3ad',
        'deep-burgundy': '#4A0E0E',
        'on-primary-fixed': '#3d0506',
        'outline-variant': '#dac1bf',
        'on-tertiary-fixed-variant': '#59422f',
        surface: '#f9f9f9',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#261900',
        'on-tertiary-container': '#a3866f',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#544341',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#5d4201',
        'surface-container-highest': '#e2e2e2',
        'surface-dim': '#dadada',
        'inverse-surface': '#2f3131',
        'on-primary-fixed-variant': '#77302d',
        'on-secondary-container': '#785a1a',
        'surface-container': '#eeeeee',
        tertiary: '#1a0b01',
        'error-container': '#ffdad6',
        'primary-container': '#4a0e0e',
        background: '#f9f9f9',
        'inverse-primary': '#ffb3ad',
        'tertiary-fixed': '#ffdcc2',
        'on-tertiary': '#ffffff',
        primary: '#2a0002',
        'on-surface': '#1a1c1c',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'container-max': '1280px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
        'section-gap': '80px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-md': ['Manrope', 'sans-serif'],
        'body-lg': ['"Work Sans"', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'headline-lg-mobile': ['Manrope', 'sans-serif'],
        'headline-display': ['Manrope', 'sans-serif'],
        'label-sm': ['"Hanken Grotesk"', 'sans-serif'],
        'body-md': ['"Work Sans"', 'sans-serif'],
        'label-bold': ['"Hanken Grotesk"', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-display': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
